### ISSUE TITLE
Timeout is too fast

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/travis-deploy-once#5]
At https://travis-ci.org/sequelize/sequelize a build takes ~8min, with 8 jobs.
Not all 8 jobs are run in parallel, so the build leader has to possibly wait more than 8min.
The 100 attempts with 3s timeout in between are not enough, as a consequence a release with https://github.com/semantic-release/semantic-release never happens.

**Comment by felixfbecker** [comment]
@gr2m this would be very important. Also wondering whether the Travis npm deployment could be used instead of `after_success`, that would handle only deploying once automatically. E.g. https://github.com/sequelize/sequelize/pull/7984

**Comment by gr2m** [comment]
I’m experimenting with using a deploy stage on travis right now for https://github.com/semantic-release/release-notes-generator, to work around  semantic-release/semantic-release#273. If that works you can use a similar setup for yourself.

We can’t use the `npm` deployment because we have some before/after logic and we also pass in credentials in a different way.
